# fly.toml app configuration file generated for rksmat-frontend on 2023-06-09T21:54:56+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rksmat-frontend"
primary_region = "waw"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[env]

[build]
  image = "ghcr.io/serykii/rks-mat:master"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"